# Generated by Django 5.0.4 on 2024-05-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
